export const allSkills = [
  "Python",
  "FastAPI",
  "PostgreSQL",
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Node.js",
  "MongoDB",
  "Pandas",
  "SQL",
  "Excel",
  "Scikit-learn",
  "TensorFlow",
  "Docker",
  "Kubernetes",
  "AWS",
  "Linux",
  "Java",
  "Spring Boot",
  "MySQL",
  "Kotlin",
  "Android SDK",
  "Firebase",
  "Swift",
  "iOS SDK",
  "Xcode",
  "Figma",
  "Adobe XD",
  "Wireframing",
  "Manual Testing",
  "Selenium",
  "Test Cases",
  "Network Security",
  "SIEM",
  "Azure",
  "Terraform",
  "Spark",
  "Hadoop",
  "Power BI",
  "C++",
  "Unity",
  "Game Physics",
  "Solidity",
  "Ethereum",
  "Web3",
  "C",
  "Microcontrollers",
  "RTOS",
  "C#",
  "ARKit",
  "Agile",
  "Roadmapping",
  "Communication",
  "Troubleshooting",
  "Networking",
  "Deep Learning",
  "Research",
  "Documentation",
  "Markdown",
  "APIs",
  "Backup",
  "Go",
  "Microservices",
  "Shell Scripting",
  "Servers",
  "DSA",
  "Problem Solving"
];

export const allLocations = [
  "Bangalore",
  "Hyderabad",
  "Pune",
  "Delhi",
  "Chennai",
  "Noida",
  "Mumbai",
  "Kolkata",
  "Gurgaon",
  "Jaipur",
  "Indore",
  "Ahmedabad",
  "Nagpur",
  "Rourkela",
  "Remote"
];

export const allRoles = [
  "Backend Developer",
  "Frontend Developer",
  "Full Stack Developer",
  "Data Analyst",
  "Machine Learning Engineer",
  "DevOps Engineer",
  "Java Developer",
  "Android Developer",
  "iOS Developer",
  "UI/UX Designer",
  "QA Engineer",
  "Cyber Security Analyst",
  "Cloud Engineer",
  "Data Engineer",
  "Business Analyst",
  "Game Developer",
  "Blockchain Developer",
  "Embedded Systems Engineer",
  "AR/VR Developer",
  "Product Manager",
  "Technical Support Engineer",
  "Site Reliability Engineer",
  "React Native Developer",
  "PHP Developer",
  "Go Developer",
  "System Administrator",
  "AI Research Intern",
  "Technical Writer",
  "Database Administrator",
  "Software Engineer Trainee"
];

export const allEducation = [
  "Student",
  "Fresher",
  "B.Tech",
  "M.Tech",
  "B.Sc",
  "M.Sc",
  "BCA",
  "MCA"
];
